# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd7f2ca32-4e3a-4d73-97fe-3aaf3197505b'
  imageRepository: 'revaturecinephiliacscinephiliacsrepo'
  containerRegistry: '03012021batchp3acr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: '03012021batchp3acr8322ae6b-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'

- script: npx ng build --prod
  displayName: ng build

# below is azure deploy
tasks:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Project-3-Training(e37a1117-750a-4552-bb20-e84ed6f3c85d)'
    appType: 'webApp'
    WebAppName: 'cinephiliacsapp'
    packageForLinux: '$(solution)/dist/CinephiliacsRepo'